-- Mercedes-Benz Spare Parts for SPARE XPRESS LTD
-- Comprehensive list for Mercedes models in Rwanda

-- Mercedes-Benz C-Class / E-Class (Sedans & Estates)
INSERT INTO products_enhanced (brand_id, model_id, category_id, product_name, slug, sku, description, short_description, price, stock_quantity, stock_status, `condition`, is_featured, is_active) VALUES
(5, 8, 1, 'Mercedes C-Class Spark Plugs', 'mercedes-c-class-spark-plugs', 'SPX-MB-C-SP-001', 'Spark plugs for Mercedes C-Class', 'Spark plugs replacement', 12500.00, 40, 'in_stock', 'new', 0, 1),
(5, 8, 1, 'Mercedes C-Class Ignition Coils', 'mercedes-c-class-ignition-coils', 'SPX-MB-C-IC-001', 'Ignition coils for Mercedes C-Class', 'Ignition coils replacement', 18500.00, 25, 'in_stock', 'new', 0, 1),
(5, 8, 1, 'Mercedes C-Class Air Fuel Filters', 'mercedes-c-class-air-fuel-filters', 'SPX-MB-C-AFF-001', 'Air and fuel filters for Mercedes C-Class', 'Air fuel filters replacement', 8500.00, 35, 'in_stock', 'new', 0, 1),
(5, 8, 1, 'Mercedes C-Class Oil Filter', 'mercedes-c-class-oil-filter', 'SPX-MB-C-OF-001', 'Oil filter for Mercedes C-Class', 'Oil filter replacement', 6500.00, 45, 'in_stock', 'new', 0, 1),
(5, 8, 1, 'Mercedes C-Class Turbocharger C200', 'mercedes-c-class-turbo-c200', 'SPX-MB-C-TUR-C200', 'Turbocharger for Mercedes C200', 'Turbocharger replacement', 185000.00, 3, 'in_stock', 'new', 0, 1),
(5, 8, 1, 'Mercedes C-Class Turbocharger C250', 'mercedes-c-class-turbo-c250', 'SPX-MB-C-TUR-C250', 'Turbocharger for Mercedes C250', 'Turbocharger replacement', 210000.00, 2, 'in_stock', 'new', 0, 1),
(5, 8, 1, 'Mercedes C-Class Turbocharger C300', 'mercedes-c-class-turbo-c300', 'SPX-MB-C-TUR-C300', 'Turbocharger for Mercedes C300', 'Turbocharger replacement', 245000.00, 2, 'in_stock', 'new', 0, 1),
(5, 8, 1, 'Mercedes C-Class Transmission Module 7G-Tronic', 'mercedes-c-class-tcm-7g', 'SPX-MB-C-TCM-7G', 'Transmission module for 7G-Tronic', 'TCM replacement', 125000.00, 4, 'in_stock', 'new', 0, 1),
(5, 8, 1, 'Mercedes C-Class Transmission Module 9G-Tronic', 'mercedes-c-class-tcm-9g', 'SPX-MB-C-TCM-9G', 'Transmission module for 9G-Tronic', 'TCM replacement', 165000.00, 3, 'in_stock', 'new', 0, 1),
(5, 8, 1, 'Mercedes C-Class Clutch Packs', 'mercedes-c-class-clutch-packs', 'SPX-MB-C-CP-001', 'Clutch packs for Mercedes C-Class', 'Clutch packs replacement', 85000.00, 5, 'in_stock', 'new', 0, 1),
(5, 8, 3, 'Mercedes C-Class Shock Absorbers', 'mercedes-c-class-shock-absorbers', 'SPX-MB-C-SA-001', 'Shock absorbers for Mercedes C-Class', 'Shock absorbers replacement', 28500.00, 18, 'in_stock', 'new', 0, 1),
(5, 8, 3, 'Mercedes C-Class AIRMATIC Components', 'mercedes-c-class-airmatic', 'SPX-MB-C-AIR-001', 'AIRMATIC components for Mercedes C-Class', 'AIRMATIC replacement', 125000.00, 4, 'in_stock', 'new', 0, 1),
(5, 8, 3, 'Mercedes C-Class Control Arms', 'mercedes-c-class-control-arms', 'SPX-MB-C-CA-001', 'Control arms for Mercedes C-Class', 'Control arms replacement', 32500.00, 14, 'in_stock', 'new', 0, 1),
(5, 8, 3, 'Mercedes C-Class Bushings', 'mercedes-c-class-bushings', 'SPX-MB-C-BUSH-001', 'Bushings for Mercedes C-Class', 'Bushings replacement', 8500.00, 30, 'in_stock', 'new', 0, 1),
(5, 8, 3, 'Mercedes C-Class Sway Bars', 'mercedes-c-class-sway-bars', 'SPX-MB-C-SB-001', 'Sway bars for Mercedes C-Class', 'Sway bars replacement', 22500.00, 12, 'in_stock', 'new', 0, 1),
(5, 8, 3, 'Mercedes C-Class Steering Rack', 'mercedes-c-class-steering-rack', 'SPX-MB-C-SR-001', 'Steering rack for Mercedes C-Class', 'Steering rack replacement', 75000.00, 5, 'in_stock', 'new', 0, 1),
(5, 8, 3, 'Mercedes C-Class Tie Rods', 'mercedes-c-class-tie-rods', 'SPX-MB-C-TR-001', 'Tie rods for Mercedes C-Class', 'Tie rods replacement', 12500.00, 20, 'in_stock', 'new', 0, 1),
(5, 8, 2, 'Mercedes C-Class Brake Pads', 'mercedes-c-class-brake-pads', 'SPX-MB-C-BP-001', 'Brake pads for Mercedes C-Class', 'Brake pads replacement', 22500.00, 20, 'in_stock', 'new', 0, 1),
(5, 8, 2, 'Mercedes C-Class Brake Discs', 'mercedes-c-class-brake-discs', 'SPX-MB-C-BD-001', 'Brake discs for Mercedes C-Class', 'Brake discs replacement', 35000.00, 16, 'in_stock', 'new', 0, 1),
(5, 8, 2, 'Mercedes C-Class Calipers', 'mercedes-c-class-calipers', 'SPX-MB-C-CAL-001', 'Brake calipers for Mercedes C-Class', 'Calipers replacement', 45000.00, 12, 'in_stock', 'new', 0, 1),
(5, 8, 2, 'Mercedes C-Class Master Cylinder', 'mercedes-c-class-master-cylinder', 'SPX-MB-C-MC-001', 'Brake master cylinder for Mercedes C-Class', 'Master cylinder replacement', 28500.00, 8, 'in_stock', 'new', 0, 1),
(5, 8, 2, 'Mercedes C-Class ABS Sensors', 'mercedes-c-class-abs-sensors', 'SPX-MB-C-ABS-001', 'ABS sensors for Mercedes C-Class', 'ABS sensors replacement', 12500.00, 25, 'in_stock', 'new', 0, 1),
(5, 8, 2, 'Mercedes C-Class ESP Sensors', 'mercedes-c-class-esp-sensors', 'SPX-MB-C-ESP-001', 'ESP sensors for Mercedes C-Class', 'ESP sensors replacement', 16500.00, 20, 'in_stock', 'new', 0, 1),
(5, 8, 4, 'Mercedes C-Class ECU', 'mercedes-c-class-ecu', 'SPX-MB-C-ECU-001', 'Engine control unit for Mercedes C-Class', 'ECU replacement', 145000.00, 3, 'in_stock', 'new', 0, 1),
(5, 8, 4, 'Mercedes C-Class TCU', 'mercedes-c-class-tcu', 'SPX-MB-C-TCU-001', 'Transmission control unit for Mercedes C-Class', 'TCU replacement', 125000.00, 4, 'in_stock', 'new', 0, 1),
(5, 8, 4, 'Mercedes C-Class Infotainment System', 'mercedes-c-class-infotainment', 'SPX-MB-C-INFO-001', 'Infotainment system for Mercedes C-Class', 'Infotainment replacement', 185000.00, 2, 'in_stock', 'new', 0, 1),
(5, 8, 4, 'Mercedes C-Class COMAND System', 'mercedes-c-class-comand', 'SPX-MB-C-COM-001', 'COMAND system for Mercedes C-Class', 'COMAND replacement', 225000.00, 2, 'in_stock', 'new', 0, 1),
(5, 8, 4, 'Mercedes C-Class Dashboard Cluster', 'mercedes-c-class-dashboard', 'SPX-MB-C-DASH-001', 'Dashboard cluster for Mercedes C-Class', 'Dashboard replacement', 95000.00, 3, 'in_stock', 'new', 0, 1),
(5, 8, 4, 'Mercedes C-Class Sensors', 'mercedes-c-class-sensors', 'SPX-MB-C-SENS-001', 'Sensors kit for Mercedes C-Class', 'Sensors replacement', 28500.00, 15, 'in_stock', 'new', 0, 1),
(5, 8, 4, 'Mercedes C-Class LED Headlights', 'mercedes-c-class-led-headlights', 'SPX-MB-C-LED-HL', 'LED headlights for Mercedes C-Class', 'LED headlights replacement', 125000.00, 4, 'in_stock', 'new', 0, 1),
(5, 8, 4, 'Mercedes C-Class Xenon Headlights', 'mercedes-c-class-xenon-headlights', 'SPX-MB-C-XEN-HL', 'Xenon headlights for Mercedes C-Class', 'Xenon headlights replacement', 95000.00, 5, 'in_stock', 'new', 0, 1),
(5, 8, 4, 'Mercedes C-Class Tail Lights', 'mercedes-c-class-tail-lights', 'SPX-MB-C-TL-001', 'Tail lights for Mercedes C-Class', 'Tail lights replacement', 65000.00, 8, 'in_stock', 'new', 0, 1),
(5, 8, 4, 'Mercedes C-Class Bumpers', 'mercedes-c-class-bumpers', 'SPX-MB-C-BMP-001', 'Bumpers for Mercedes C-Class', 'Bumpers replacement', 85000.00, 6, 'in_stock', 'new', 0, 1),
(5, 8, 4, 'Mercedes C-Class Mirrors', 'mercedes-c-class-mirrors', 'SPX-MB-C-MIR-001', 'Mirrors for Mercedes C-Class', 'Mirrors replacement', 35000.00, 10, 'in_stock', 'new', 0, 1),
(5, 8, 4, 'Mercedes C-Class Grille', 'mercedes-c-class-grille', 'SPX-MB-C-GRL-001', 'Grille for Mercedes C-Class', 'Grille replacement', 45000.00, 7, 'in_stock', 'new', 0, 1),
(5, 8, 4, 'Mercedes C-Class Door Handles', 'mercedes-c-class-door-handles', 'SPX-MB-C-DH-001', 'Door handles for Mercedes C-Class', 'Door handles replacement', 12500.00, 15, 'in_stock', 'new', 0, 1),
(5, 8, 4, 'Mercedes C-Class Window Regulators', 'mercedes-c-class-window-regulators', 'SPX-MB-C-WR-001', 'Window regulators for Mercedes C-Class', 'Window regulators replacement', 22500.00, 12, 'in_stock', 'new', 0, 1),
(5, 8, 7, 'Mercedes C-Class Engine Oil', 'mercedes-c-class-engine-oil', 'SPX-MB-C-EO-001', 'Engine oil for Mercedes C-Class', 'Engine oil replacement', 12500.00, 40, 'in_stock', 'new', 0, 1),
(5, 8, 7, 'Mercedes C-Class Brake Fluid', 'mercedes-c-class-brake-fluid', 'SPX-MB-C-BF-001', 'Brake fluid for Mercedes C-Class', 'Brake fluid replacement', 8500.00, 35, 'in_stock', 'new', 0, 1),
(5, 8, 7, 'Mercedes C-Class Coolant', 'mercedes-c-class-coolant', 'SPX-MB-C-COOL-001', 'Coolant for Mercedes C-Class', 'Coolant replacement', 9500.00, 30, 'in_stock', 'new', 0, 1),
(5, 8, 7, 'Mercedes C-Class Cabin Filter', 'mercedes-c-class-cabin-filter', 'SPX-MB-C-CAF-001', 'Cabin air filter for Mercedes C-Class', 'Cabin filter replacement', 6500.00, 40, 'in_stock', 'new', 0, 1),
(5, 8, 7, 'Mercedes C-Class Wiper Blades', 'mercedes-c-class-wiper-blades', 'SPX-MB-C-WB-001', 'Wiper blades for Mercedes C-Class', 'Wiper blades replacement', 8500.00, 25, 'in_stock', 'new', 0, 1),
(5, 8, 7, 'Mercedes C-Class Tires', 'mercedes-c-class-tires', 'SPX-MB-C-TIR-001', 'Tires for Mercedes C-Class', 'Tires replacement', 165000.00, 4, 'in_stock', 'new', 0, 1),
(5, 8, 7, 'Mercedes C-Class Wheel Bearings', 'mercedes-c-class-wheel-bearings', 'SPX-MB-C-WHB-001', 'Wheel bearings for Mercedes C-Class', 'Wheel bearings replacement', 22500.00, 18, 'in_stock', 'new', 0, 1);

-- Mercedes-Benz G-Class (G300 / G350 / G500 / AMG G63)
INSERT INTO products_enhanced (brand_id, model_id, category_id, product_name, slug, sku, description, short_description, price, stock_quantity, stock_status, `condition`, is_featured, is_active) VALUES
(5, 184, 3, 'Mercedes G-Class Heavy Duty Suspension', 'mercedes-g-class-heavy-suspension', 'SPX-MB-G-HS-001', 'Heavy duty suspension for Mercedes G-Class', 'Heavy suspension replacement', 185000.00, 3, 'in_stock', 'new', 0, 1),
(5, 184, 3, 'Mercedes G-Class Solid Axles', 'mercedes-g-class-solid-axles', 'SPX-MB-G-SA-001', 'Solid axles for Mercedes G-Class', 'Solid axles replacement', 285000.00, 2, 'in_stock', 'new', 0, 1),
(5, 184, 1, 'Mercedes G-Class Transfer Case', 'mercedes-g-class-transfer-case', 'SPX-MB-G-TC-001', 'Transfer case for Mercedes G-Class', 'Transfer case replacement', 225000.00, 2, 'in_stock', 'new', 0, 1),
(5, 184, 1, 'Mercedes G-Class 4WD Components', 'mercedes-g-class-4wd-components', 'SPX-MB-G-4WD-001', '4WD components for Mercedes G-Class', '4WD components replacement', 165000.00, 3, 'in_stock', 'new', 0, 1),
(5, 184, 2, 'Mercedes G-Class High Performance Brakes', 'mercedes-g-class-high-performance-brakes', 'SPX-MB-G-HPB-001', 'High performance brakes for AMG G63', 'High performance brakes replacement', 325000.00, 2, 'in_stock', 'new', 0, 1),
(5, 184, 1, 'Mercedes G-Class Turbocharger G500', 'mercedes-g-class-turbo-g500', 'SPX-MB-G-TUR-G500', 'Turbocharger for Mercedes G500', 'Turbocharger replacement', 285000.00, 2, 'in_stock', 'new', 0, 1),
(5, 184, 1, 'Mercedes G-Class Turbocharger AMG G63', 'mercedes-g-class-turbo-amg-g63', 'SPX-MB-G-TUR-AMG', 'Twin turbochargers for AMG G63', 'Twin turbochargers replacement', 650000.00, 1, 'in_stock', 'new', 0, 1);